name: Update Profile Readme - status

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Fetch Values from Vercel App
        run: |
            FOLLOWERS=$(curl -s https://profile-readme-stats-git-main-grem6.vercel.app/api/followers)
            REPOSITORIES=$(curl -s https://profile-readme-stats-git-main-grem6.vercel.app/api/repositories)
            COMMITS=$(curl -s https://profile-readme-stats-git-main-grem6.vercel.app/api/commits)
            
            echo "FOLLOWERS: $FOLLOWERS"
            echo "REPOSITORIES: $REPOSITORIES"
            echo "COMMITS: $COMMITS"
            
            sed "s/FOLLOW/$FOLLOWERS/g" README.template.md > README.md.tmp
            sed -i "s/REPO_PH/$REPOSITORIES/g" README.md.tmp
            sed -i "s/COMMITS/$COMMITS/g" README.md.tmp




      - name: Commit and Push Changes
        run: |
          mv README.md.tmp README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git add .
          git commit -m "Update README.md - status"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
